site_name: Nanang Git
site_url: https://nanangsb.github.io/jurnal/

repo_name: nanangsb/jurnal
repo_url: https://github.com/nanangsb/jurnal

copyright: Copyright &copy; 2016 - 2024 nanang.id
theme:
  name: material
  custom_dir: templates
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
   
    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - footnotes
  - tables
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

plugins:
  - blog:
      pagination_per_page: 5
      pagination_url_format: "{page}"
      pagination_format: "$link_first $link_previous ~2~ $link_next $link_last"
      blog_toc: true
      post_date_format: full
      post_url_format: "{slug}"
      post_excerpt: optional
      post_excerpt_separator: <!-- more -->
      archive_date_format: MMMM yyyy
      archive_toc: true
      categories_name: Kategori
      categories_toc: true
  - privacy
  - search
  - glightbox
  - tags:
      tags_file: tags.md
  - rss:
      enabled: !ENV [CI, false]
      match_path: blog/post/.*
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags 
  
extra:
  consent:
    actions:
      - accept
      - reject
      - manage
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of our documentation and whether users find what they're searching for. With your consent, you're helping us to make our documentation better.
    cookies:
      analytics: Google Analytics 
      github: Github
      
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js
